sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs/test
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs/doc
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs/mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs/headerCheck scalajs-js-envs/test:headerCheck
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs-test-kit/test
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs-test-kit/doc
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs-test-kit/mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-js-envs-test-kit/headerCheck scalajs-js-envs-test-kit/test:headerCheck
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-nodejs/test
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-nodejs/doc
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-nodejs/mimaReportBinaryIssues
  - sbt ++$TRAVIS_SCALA_VERSION scalajs-env-nodejs/headerCheck scalajs-env-nodejs/test:headerCheck
scala:
  - 2.11.12
  - 2.12.11
  - 2.13.2
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.cache/coursier"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
